In [3]:
#エクセルファイルの変換を目指して
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
file_name = 'B39 restraint R2'
file = pd.ExcelFile(file_name+'.xls')
#all_df = pd.DataFrame()
time_file = open(file_name+'_time_data.csv', 'w')


sheet_df = file.parse(file.sheet_names, header=None)
all_df = pd.DataFrame()

sheet_names = file.sheet_names

"""
for j, name in enumerate(sheet_names):
    sheet_df[j] = file.parse(name)
"""




for i, name in enumerate(sheet_names):
    sheet_df[i] = file.parse(name)
    end_number = (np.where(sheet_df[i]['INFORMATION']=="CHANNEL")[0][1])
    sig1 = (sheet_df[i]['INFORMATION'][21:end_number-2])
    #sig1 = sig1 - sig1.mean()
    sig1 = sig1.values
    print(len(sig1))
    print(sig1)
    #print(type(sig1))
    #print(sig1[0])

       

file.close()
time_file.close()
#print(all_df)

#import xlrd
#file = xlrd.open_workbook('B39 restraint R2.xls')
#print(file.nsheets)

#all_df.to_csv("otamesi.csv", header=False, index=False)


1285
[0.01672 0.1098 0.06153 ... 0.05326 0.07325 0.05809]
1438
[-0.19667 -0.16426 -0.13151 ... 0.22045 0.15961 0.14978]
1395
[0.04413 0.06688 0.1615 ... 0.18271 0.18529 0.16736]
1044
[0.04516 0.06136 0.0374 ... -0.01879 -0.08463 -0.15961]
1069
[0.22873 0.23579 0.29388 ... 0.43918 0.41746 0.39661]
1318
[0.26544 0.27251 0.2451 ... 0.01999 0.01672 0.01379]
1006
[-0.13565 -0.15875 -0.15254 ... 0.1098 0.0574 0.11324]
1193
[-0.12341 -0.15857 -0.03482 ... 0.05326 0.09842 0.10462]
2173
[-0.06877 -0.08377 -0.03189 ... 0.17391 0.20787 0.13996]
2438
[-0.10876 -0.13806 -0.20753 ... -0.00103 -0.0493 -0.01224]
1443
[-0.12565 -0.14565 -0.0755 ... -0.11273 -0.02534 0.0181]
1173
[0.04964 0.08498 0.10945 ... 0.05343 0.10549 0.10014]
2090
[-0.02965 0.11428 0.09773 ... 0.13496 0.09256 -0.0181]
2239
[-0.20546 -0.11324 -0.1322 ... 0.04861 0.00017 -0.03154]
1450
[0.08377 0.00982 0.03189 ... -0.01637 -0.0324 -0.00517]
1110
[0.12186 0.13651 0.13531 ... 0.10342 0.13203 0.15202]
982
[0.18408 0.06395 -0.09187 -0.

In [ ]:
#エクセルファイルの変換を目指して
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
file_name = 'B39 restraint R2'
file = pd.ExcelFile(file_name+'.xls')
#all_df = pd.DataFrame()
time_file = open(file_name+'_time_data.csv', 'w')


sheet_df = file.parse(file.sheet_names, header=None)
all_df = pd.DataFrame()

sheet_names = file.sheet_names
for j, name in enumerate(sheet_names):
    sheet_df[j] = file.parse(name)
    
for i, name in enumerate(sheet_names):
    sheet_df[i] = file.parse(name)
    end_number = (np.where(sheet_df[i]['INFORMATION']=="CHANNEL")[0][1])
    sig1 = (sheet_df[i]['INFORMATION'][21:end_number-2])
    sig1 = sig1 - sig1.mean()

    for j in range(0, 30):
        end_number = (np.where(sheet_df[j]['INFORMATION']=="CHANNEL")[0][1])
        sig2 = (sheet_df[j]['INFORMATION'][21:end_number-2])
        sig2 = sig2 - sig2.mean()
        corr = np.correlate(sig1, sig2, "full")
        estimated_delay = corr.argmax() - (len(sig1) - 1)
        print("estimated delay is " + str(estimated_delay)+ "_" + str(i) +"_"+ str(j))

        plt.figure(figsize=(6, 4), dpi=30)
        plt.subplots_adjust(wspace=0.4, hspace=0.6)
        plt.subplot(4, 1, 1)
        plt.ylabel("sig"+str(i))
        plt.plot(sig1)
        
        plt.subplot(4, 1, 2)
        plt.ylabel("sig"+str(j))
        plt.plot(sig2, color="g")

        plt.subplot(4, 1, 3)
        plt.ylabel("fit")
        plt.plot(np.arange(len(sig1)), sig1)
        plt.plot(np.arange(len(sig2)) + estimated_delay, sig2 )
        plt.xlim([0, len(sig1)])

        plt.subplot(4, 1, 4)
        plt.ylabel("corr")
        plt.plot(np.arange(len(corr)) - len(sig2) + 1, corr, color="r")
        plt.xlim([0, len(sig1)])
        #plt.show()
        print(i,j)
        plt.plot()
        #plt.savefig("./image2/"+ str(i) +"_"+ str(j) +".png")
        

file.close()
time_file.close()
#print(all_df)

#import xlrd
#file = xlrd.open_workbook('B39 restraint R2.xls')
#print(file.nsheets)

#all_df.to_csv("otamesi.csv", header=False, index=False)


In [33]:
#エクセルファイルの変換を目指して(最大値の導出)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
file_name = 'B39 restraint R2'
file = pd.ExcelFile(file_name+'.xls')
#all_df = pd.DataFrame()
time_file = open(file_name+'_time_data.csv', 'w')


sheet_df = file.parse(file.sheet_names, header=None)
all_df = pd.DataFrame()

sheet_names = file.sheet_names
for j, name in enumerate(sheet_names):
    sheet_df[j] = file.parse(name)
J=j
print(J)
print(len(sheet_names))
    
for i, name in enumerate(sheet_names):
    sheet_df[i] = file.parse(name)
    end_number = (np.where(sheet_df[i]['INFORMATION']=="CHANNEL")[0][1])
    sig1 = (sheet_df[i]['INFORMATION'][21:end_number-2])
    sig1 = sig1 - sig1.mean()

    for j in range(i+1, 30):
        end_number = (np.where(sheet_df[j]['INFORMATION']=="CHANNEL")[0][1])
        sig2 = (sheet_df[j]['INFORMATION'][21:end_number-2])
        sig2 = sig2 - sig2.mean()
        corr = np.correlate(sig1, sig2)#, "full")
        print(np.max(corr))
        print(np.argmax(corr))
        #print(corr.dtype)
        #a_float = corr.astype(np.float32)
        #print(a_float)
        #a=np.amax(corr)
        #print(type(a))
        #print(np.max(a))
        #print(a_float.max(axis=0))
        #print(np.arange(len(corr)) - len(sig2) + 1)


file.close()
time_file.close()
#print(all_df)

#import xlrd
#file = xlrd.open_workbook('B39 restraint R2.xls')
#print(file.nsheets)

#all_df.to_csv("otamesi.csv", header=False, index=False)


29
30
30.643688907836182
89
49.76631359301486
27
26.027854097480883
59
20.60537222217791
119
8.42587197496887
0
28.716862082982708
266
30.606666441991738
78
55.06327926296151
355
28.678840754635416
481
15.046191746929178
75
47.56275851938326
36
40.19165943879421
113
26.759708365704686
187
22.842521638377455
68
14.124233495729833
76
33.62026473901978
251
35.107080209809425
129
17.12813553378189
13
28.073914456234917
160
43.374096487012146
27
37.36477613402164
206
24.84395050145023
593
20.235467478268063
17
5.695928737968055
42
44.55021098257482
569
25.22453895092369
875
30.14860112415487
1
46.78426663541315
71
53.88154957214704
272
9.828001829851027
43
30.51580275298584
294
19.44273225273632
248
19.991372423619882
112
20.537403170111965
227
26.993752876148513
124
48.59070170874035
363
46.063277405531345
143
4.474718220279548
0
43.495892845592024
84
36.85788717616439
578
26.757499840765806
440
-3.7990197220303163
12
25.0900473188112
0
22.851449866406156
386
36.55901146912195
31
52.898089

In [30]:
#自己相関を求めるために
import pandas as pd
import numpy as np
deta = pd.read_csv('otamesi.csv')
#print(deta)

#print(deta[:,0])
sig1 = deta.values[:,0]
sig2 = deta.values[:,1]
sig1_float = sig1.astype(np.float32)
print(sig1_float)


#sig1 = sig1[~np.isnan(sig1).any(axis=1)]
print(sig1[~np.isnan(sig1)])
print(sig1)
  
#np_data[0] = np_data[0] - np_data[0].mean()
#np_data[1] = np_data[1] - np_data[1].mean()
sig1 = sig1 - sig1.mean()
sig2 = sig2 - sig2.mean()

corr = np.correlate(sig1, sig2, "full")
estimated_delay = corr.argmax() - (len(sig1) - 1)
print("estimated delay is " + str(estimated_delay))

ValueError: could not convert string to float: 'START'

In [6]:
#時間データから自己相関を求めるために
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
from pylab import *
with open('/yuni/txt-data/restraint/B39 Rd.pickle', mode='rb') as fp:
    df = pickle.load(fp)


time_file = open(file_name+'_time_data.csv', 'r')

starttime = time_file[0][0]
endtime = time_file[0][1]
start = int(starttime/0.00004)
end = int(endtime/0.00004)
datatime = []
#print(df[start:end])
#specdatab = np.array(df[start:end])
for i in range(len(df[start:end])):
#    print(i)
    datatime.append([(starttime+(i*0.00004))])
    
plt.figure(figsize=(10,4))
plt.subplots_adjust(wspace=0.0, hspace=-0.4)

FileNotFoundError: [Errno 2] No such file or directory: '~/yuni/txt-data/restraint/B39 Rd.pickle'

In [10]:
import pandas as pd
import numpy as np
import sys
import os.path


#file_name = sys.argv[1]
file_name = "B32-restraint-L3.xls"     

#前後のとる範囲(s)                                                                                                                                                                                                                            
ds = 0.5

name, ext = os.path.splitext(file_name)
file = pd.ExcelFile(file_name)
time_file = open(name+'_ripple_data.csv', 'w')



sheet_df = file.parse(file.sheet_names, header=None)
all_df = pd.DataFrame()

sheet_names = file.sheet_names
for i, sheet_name in enumerate(sheet_names):
    sheet_df[i] = file.parse(sheet_name)
    start_time = sheet_df[i]['Unnamed: 1'][(np.where(sheet_df[i]['INFORMATION']=="START")[0][0])]
    if sheet_df[i]['Unnamed: 1'][(np.where(sheet_df[i]['INFORMATION']=="START")[0][0])-1] == 25000 :
        end_time = (np.where(sheet_df[i]['INFORMATION']=="START")[0][1]*4)/100000 + start_time
    else :
        end_time = (np.where(sheet_df[i]['INFORMATION']=="START")[0][1]*6)/100000 + start_time
    print("{:.6f},{:.6f}".format(start_time, end_time), file=time_file)

file.close()
time_file.close()

In [17]:
#エクセルファイルの変換を目指して                                                                                                                                                                                                             
import pandas as pd
import numpy as np
import sys
import os.path


#file_name = sys.argv[1]
#file_name = "B34-female-L3.xls"

#前後のとる範囲(s)                                                                                                                                                                                                                            
ds = 0.5

data = np.loadtxt(name+'_ripple_data.csv', delimiter=",")
time_file = open(name+'_time_data.csv', 'w')
label_file = open(name+'_label_data.csv', 'w')
print(data)
x = np.sort(data, axis=0)
#data.sort()
print(x)
np.savetxt('out1.csv',x,delimiter=',')
print(len(x))
k=0

for i in range(0, len(x)-1) :     
    if( x[i-k][1] >= x[i+1-k][0] ) :  
        x[i-k][1] = x[i+1-k][1]
        x = np.delete(x, i+1-k, 0)
        k = k+1

np.savetxt('out2.csv',x,delimiter=',')


print(x)
print(len(x))


[[2083.26524 2083.302  ]
 [2076.5666  2076.63588]
 [2082.39444 2082.48512]
 [2073.06248 2073.15392]
 [2041.49928 2041.5692 ]
 [2036.78692 2036.86248]
 [2019.30344 2019.39592]
 [2017.89968 2018.00464]
 [2016.69868 2016.75368]
 [1993.10344 1993.16608]
 [1988.08728 1988.25256]
 [1960.97576 1961.05724]
 [1898.02624 1898.05736]
 [1875.83416 1875.9262 ]
 [1867.70764 1867.81408]
 [1864.5844  1864.62852]
 [1861.525   1861.60096]
 [1825.2544  1825.32444]
 [1806.34836 1806.47236]
 [1792.6178  1792.67408]
 [1789.07504 1789.15248]
 [1780.3242  1780.41332]
 [1776.59544 1776.68496]
 [1769.9294  1770.0096 ]
 [1761.51064 1761.60564]
 [1745.2718  1745.44172]
 [1703.31612 1703.39756]
 [1700.72632 1700.77732]
 [1690.99672 1691.09216]
 [1680.67472 1680.731  ]]
[[1680.67472 1680.731  ]
 [1690.99672 1691.09216]
 [1700.72632 1700.77732]
 [1703.31612 1703.39756]
 [1745.2718  1745.44172]
 [1761.51064 1761.60564]
 [1769.9294  1770.0096 ]
 [1776.59544 1776.68496]
 [1780.3242  1780.41332]
 [1789.07504 1789.15248]

In [ ]:
start_cut = x[0][0] - ds

for i in range(0, len(x)-1) :
    if(x[i][1]+(2*ds) < x[i+1][0]) :
        print("{:.6f},{:.6f},{:.6f},{:.6f}".format(start_cut, x[i][1]+ds, x[i][0], x[i][1]), file=label_file)
        print("{:.6f},{:6f}".format(start_cut, x[i][1]+ds), file=time_file)
        start_cut = x[i+1][0]-ds
    else :
        diff = (x[i+1][0] - x[i][1])/2
        print("{:.6f},{:.6f},{:.6f},{:.6f}".format(start_cut, x[i][1]+diff, x[i][0], x[i][1]), file=label_file)
        print("{:.6f},{:.6f}".format(start_cut, x[i][1]+diff), file=time_file)
        start_cut = x[i+1][0]-diff

print("{:.6f},{:.6f},{:.6f},{:.6f}".format(start_cut, x[(len(x)-1)][1]+ds, x[(len(x)-1)][0], x[(len(x)-1)][1]), file=label_file)
print("{:.6f},{:.6f}".format(start_cut, x[(len(x)-1)][1]+ds), file=time_file)
time_file.close()
label_file.close()
print(sys.argv[1]+"----end")